# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:

- task: Bash@3
  displayName: "Select Latest Xcode Version"
  inputs:
    targetType: 'inline'
    script: |
      latest_xcode=$(ls /Applications | grep 'Xcode' | sort -Vr | head -n 1)
      sudo xcode-select -s "/Applications/$latest_xcode"
      latest_xcode_path=$(xcrun xcode-select --print-path)
      xcodebuild -version

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'businesscard'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: "$latest_xcode_path"
    packageApp: true
    exportMethod: 'ad-hoc'