trigger:
  branches:
    include:
      - main
  paths:
    include:
      - build/*.ipa

pool:
  vmImage: 'macOS-latest'

stages:
  - stage: Upload
    displayName: 'Upload to TestFlight'
    jobs:
      - job: UploadIPA
        displayName: 'Upload prebuilt IPA to TestFlight'
        steps:
          - checkout: self
            displayName: 'Checkout Repository'
            env:
              apiKeyId: $(myApiKeyId)
              apiKeyIssuerId: $(myApiKeyIssuerId)
              apitoken: $(myApitoken)
          - task: AppStoreRelease@1
            displayName: "Publish to AppStore TestFlight (Fastlane)"
            inputs:
              authType: "ApiKey"
              apiKeyId: "$(apiKeyId)"
              apiKeyIssuerId: "$(apiKeyIssuerId)"
              apitoken: "$(apitoken)"
              releaseTrack: "TestFlight"
              appType: "iOS"
              ipaPath: "./BusinessCard.ipa"
              appSpecificId: "$(appSpecificId)"
              releaseNotes: "./release.txt"
              distributedToExternalTesters: true
              externalTestersGroups: "Appdome"