# Minimal pipeline - just uploads pre-built IPA
name: TestFlight-Upload-$(Date:yyyyMMdd)-$(Rev:r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - build/*.ipa

pool:
  vmImage: 'macOS-latest'

stages:
  - stage: Upload
    displayName: 'Upload to TestFlight'
    jobs:
      - job: UploadIPA
        displayName: 'Upload Pre-built IPA'
        steps:
          - checkout: self
            displayName: 'Checkout Repository'

          - task: Bash@3
            displayName: 'Validate IPA Exists'
            inputs:
              targetType: 'inline'
              script: |
                IPA_FILE=$(find build/ -name "*.ipa" -type f | head -1)
                if [ -z "$IPA_FILE" ]; then
                  echo "❌ No IPA found in build/ folder"
                  echo "Please build locally and commit IPA to build/ folder"
                  exit 1
                fi
                echo "✅ Found IPA: $IPA_FILE"
                echo "##vso[task.setvariable variable=ipaPath]$IPA_FILE"

          - task: AppStoreRelease@1
            displayName: 'Upload to TestFlight'
            inputs:
              serviceEndpoint: 'AppStore-BusinessCard-TestFlight'
              applicationIdentifier: 'com.gleidsonlm.businesscard'
              appType: 'iOS'
              ipaPath: '$(ipaPath)'
              releaseTrack: 'TestFlight'
              releaseNotes: |
                Business Card App - Manual Build
                
                Built locally with Xcode
                Version managed manually for quality control
                
                Please test and provide feedback via TestFlight